refactor: logic moves to phal
mikejgray/neon-homeassistant-skill pull request #21
Opened 2023-05-23 01:46 UTC by mikejgray

# Description
Passing messages back and forth along the bus for devices is wasteful (too many API calls) and can obscure troubleshooting efforts. Also, when CommonIOT gets introduced in OVOS 0.0.9, all the logic will be moved to the OVOS core libraries. This effort gets us closer to that, helps minimize bugs, improves troubleshooting, and simplifies testing efforts on the skill itself.

# Issues
N/A

# Other Notes
These aren't breaking changes, necessarily, but it's a large refactor.

2023-05-27 02:19 UTC, NeonDaniel approved these changes, later dismissed
Didn't fully read through but tested and verified working

2023-05-27 02:19 UTC, NeonDaniel commented on pyproject.toml
> +version = "0.0.12a11"
mismatch with `version.py`

2023-05-27 02:19 UTC, NeonDaniel commented on requirements.txt
> +adapt-parser @ git+https://github.com/mycroftai/adapt@HEAD ; python_version >= "3.7" and python_version < "4.0"
Looks like very verbose output from something; these dependencies will break compat if enforced

2023-05-27 02:25 UTC, mikejgray commented on requirements.txt
> +adapt-parser @ git+https://github.com/mycroftai/adapt@HEAD ; python_version >= "3.7" and python_version < "4.0"
Yeah, `poetry export`...let me tidy up

2023-05-27 02:46 UTC, NeonDaniel requested changes

2023-05-27 02:46 UTC, NeonDaniel commented on requirements.txt
> +ovos-workshop~=0.0.12a7
If this is for a stable release and it requires newer than `0.0.11`, please pin a max version `<=0.0.12` to prevent future updates to alpha versions

2023-05-27 02:46 UTC, NeonDaniel commented on skill.json
> +            "pfzy==0.3.4",
out of sync with requirements.txt; consider implementing automation used in Neon skills

2023-05-27 03:01 UTC, NeonDaniel commented on requirements.txt
> +ovos-workshop~=0.0.12a7
Sorry, still needs the minimum spec if you need that alpha, so full string would be `>=0.0.12a7,<0.0.12`

2023-05-30 20:32 UTC, NeonDaniel approved these changes

2023-05-30 20:45 UTC, merged