chore/Update Dependencies
mikejgray/neon-homeassistant-skill pull request #31
Opened 2024-01-02 18:22 UTC by NeonDaniel

# Description
Removes ovos-core dependency which isn't directly used/referenced in the skill
Updates ovos-workshop dependency spec to support latest stable release

# Issues

# Other Notes

2024-01-02 18:34 UTC, NeonDaniel commented
Is there a reason the `skill_id` is [overridden in init](https://github.com/mikejgray/neon-homeassistant-skill/blob/f15c17c9d955489d480969aa36c3216ba4c32be5/neon_homeassistant_skill/__init__.py#L21)? I think this could cause some issues since it is set during load to something different and then overridden here

2024-01-02 18:40 UTC, mikejgray requested changes
Rather than removing, can we break off into requirements-dev.txt?

2024-01-02 18:49 UTC, mikejgray commented
> Is there a reason the `skill_id` is [overridden in init](https://github.com/mikejgray/neon-homeassistant-skill/blob/f15c17c9d955489d480969aa36c3216ba4c32be5/neon_homeassistant_skill/__init__.py#L21)? I think this could cause some issues since it is set during load to something different and then overridden here

Probably lack of knowledge on my part when I wrote it. We can change that

2024-01-03 04:57 UTC, mikejgray approved these changes

2024-01-03 06:13 UTC, merged