Add some options to control "chattiness" of the plugin
mikejgray/neon-homeassistant-skill pull request #40
Opened 2024-03-10 21:00 UTC by jumper047

I added two options to your plugin:
- Skip `acknowledge` dialogue completely (I believe it is have not too much of useful information, because just after it another dialog started which actually duplicates information from first one. In fact, I'd suggest to get rid of it completely). Option disabled by default.
- Skip confirmation dialogue in actions for certain entities. Usecase: control lights in the same room as Mycroft. I don't need additional confirmation that lights are turned on if they are turned on.

Settings file example with new params:
```
{
    "verbose": false,
    "silent_entities": [
        "hallway lamp"
    ],
    "__mycroft_skill_firstrun": false,
    "connected": true
}
```

2024-03-12 05:00 UTC, mikejgray requested changes
Hi, thank you for this contribution! I appreciate it very much.

I'm not opposed to anything here, but would you please add a log message if `verbose` is True, as there will be no indication to the user if their request failed or succeeded without that. Since this is an async process that hits the PHAL plugin, which may or may not ever respond, that log would make troubleshooting issues much easier. `self.log.info()` level should be fine.

2024-03-12 21:42 UTC, jumper047 commented
Makes sense, thank you for feedback! Now it will be phrase or log entry.
BTW, I changed and force-pushed commits, is it ok or is it better to add new commits with fixes?

2024-03-15 21:49 UTC, mikejgray commented
> Makes sense, thank you for feedback! Now it will be phrase or log entry. BTW, I changed and force-pushed commits, is it ok or is it better to add new commits with fixes?

Generally, I prefer new commits, as it makes it more clear what the history of the PR was. We squash commits on merge so there's no need to force-push anything

2024-03-15 21:53 UTC, mikejgray requested changes

2024-03-15 21:53 UTC, mikejgray commented on neon_homeassistant_skill/__init__.py
> +                self.log.info("Trying to get device status")
```suggestion
                self.log.info(f"Trying to get device status for {device}")
```

2024-03-15 21:53 UTC, mikejgray commented on neon_homeassistant_skill/__init__.py
> +                self.log.info("Trying to turn on device")
```suggestion
                self.log.info(f"Trying to turn on device {device}")
```

2024-03-15 21:53 UTC, mikejgray commented on neon_homeassistant_skill/__init__.py
> +                self.log.info("Trying to turn off device")
```suggestion
                self.log.info(f"Trying to turn off device {device}")
```

2024-03-15 21:53 UTC, mikejgray commented on neon_homeassistant_skill/__init__.py
> +                self.log.info("Trying to set brightness")
```suggestion
                self.log.info(f"Trying to set brightness for {device}")
```

2024-03-15 21:53 UTC, mikejgray commented on neon_homeassistant_skill/__init__.py
> +                self.log.info("Trying to increase brightness")
```suggestion
                self.log.info(f"Trying to increase brightness for {device}")
```

2024-03-15 21:53 UTC, mikejgray commented on neon_homeassistant_skill/__init__.py
> +                self.log.info("Trying to decrease brightness")
```suggestion
                self.log.info(f"Trying to decrease brightness for {device}")
```

2024-03-15 21:53 UTC, mikejgray commented on neon_homeassistant_skill/__init__.py
> +                self.log.info("Trying to set light color")
```suggestion
                self.log.info(f"Trying to set color of {device}")
```

2024-03-15 21:53 UTC, mikejgray commented on neon_homeassistant_skill/__init__.py
> +                self.log.info("Trying to pass message to Home Assistant's Assist API")
```suggestion
                self.log.info(f"Trying to pass message to Home Assistant's Assist API:\n{command}")
```

2024-05-18 02:04 UTC, mikejgray approved these changes

2024-05-18 02:05 UTC, merged